#!/usr/bin/env python3
"""
Fetch CoinMarketCap's latest Fear & Greed index and write it to data/fng.js.
Run manually or via cron: 10 0 * * * cd /path/to/btcticker && python3 fetch_fng.py

The CMC API requires a private key — never embed it in committed files or any
client-side code. Supply it via the CMC_API_KEY environment variable (a GitHub
Actions secret in CI):

    CMC_API_KEY=xxxxxxxx python3 fetch_fng.py
"""

import json
import os
import sys
import tempfile
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

OUT_FILE = Path(__file__).parent / "data" / "fng.js"
URL      = "https://pro-api.coinmarketcap.com/v3/fear-and-greed/latest"


def main():
    api_key = os.environ.get("CMC_API_KEY")
    if not api_key:
        sys.exit("ERROR: CMC_API_KEY environment variable is not set")

    print("Fetching Fear & Greed index from CoinMarketCap...")
    req = urllib.request.Request(URL, headers={
        "X-CMC_PRO_API_KEY": api_key,
        "Accept":            "application/json",
        "User-Agent":        "btcticker-fng/1.0",
    })
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            raw = json.loads(resp.read())
    except urllib.error.HTTPError as e:
        sys.exit(f"ERROR: CMC returned HTTP {e.code}: {e.read().decode('utf-8', 'replace')}")
    except Exception as e:
        sys.exit(f"ERROR: CMC fetch failed: {e}")

    status = raw.get("status") or {}
    # error_code comes back as a string ("0" on success), so compare loosely
    if str(status.get("error_code", "0")) not in ("0", ""):
        sys.exit(f"ERROR: CMC returned error {status.get('error_code')}: {status.get('error_message')}")

    # Response: {"data": {"value": 73, "value_classification": "Greed",
    #            "update_time": "2023-..."}, "status": {...}}
    data = raw.get("data") or {}
    try:
        value = int(round(float(data["value"])))
    except (KeyError, TypeError, ValueError):
        sys.exit(f"ERROR: no usable value in CMC response: {data}")
    classification = data.get("value_classification", "")

    payload = {
        "generated":      datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "update_time":    data.get("update_time", ""),
        "value":          value,
        "classification": classification,
    }

    js = (
        "// Auto-generated by fetch_fng.py -- do not edit manually\n"
        f"window.LOCAL_FNG = {json.dumps(payload, separators=(',', ':'))};\n"
    )
    # atomic replace so an interrupted run can't leave a truncated fng.js
    fd, tmp = tempfile.mkstemp(dir=OUT_FILE.parent, suffix=".tmp")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(js)
    os.replace(tmp, OUT_FILE)
    print(f"Written {OUT_FILE}: value={value} ({classification})")


if __name__ == "__main__":
    main()
