#!/usr/bin/env python3
"""
Fetch CoinMarketCap's latest Fear & Greed index and write it to data/fng.js.
Run manually or via cron: 10 0 * * * cd /path/to/btcticker && python3 fetch_fng.py

The CMC API requires a private key — never embed it in committed files or any
client-side code. Supply it via the CMC_API_KEY environment variable (a GitHub
Actions secret in CI):

    CMC_API_KEY=xxxxxxxx python3 fetch_fng.py
"""

import json
import os
import sys
import tempfile
import time
import urllib.error    # HTTPError is used below; urllib.request only imports
import urllib.request  # it transitively, which isn't a guarantee to rely on
from datetime import datetime, timezone
from pathlib import Path

OUT_FILE = Path(__file__).parent / "data" / "fng.js"
URL      = "https://pro-api.coinmarketcap.com/v3/fear-and-greed/latest"

# The workflow commits data/fng.js whenever the bytes change. `generated` is a
# wall-clock stamp, so writing unconditionally turns a 6-hourly cron into 4
# commits a day even when the index hasn't moved (measured: ~46% of runs carry
# no real change). Write only when the reading itself changed, or when the
# on-disk stamp is old enough that app.js's 48h staleness check would start
# flagging a healthy pipeline as broken. `update_time` is deliberately not a
# semantic field: CMC bumps it on almost every poll regardless of whether the
# index moved, so including it would defeat the point of this guard.
SEMANTIC_FIELDS = ("value", "classification")
HEARTBEAT_SEC   = 20 * 3600

MAX_ATTEMPTS = 3
BACKOFF_SEC  = 5


def read_existing(path):
    """Payload from a previously generated file; None if absent or unparseable."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end == -1:
        return None
    try:
        return json.loads(text[start:end + 1])
    except json.JSONDecodeError:
        return None


def should_write(old, new, now, heartbeat_sec=HEARTBEAT_SEC):
    """True when the payload carries new information, or the stamp needs refreshing."""
    if old is None:
        return True
    if any(old.get(f) != new.get(f) for f in SEMANTIC_FIELDS):
        return True
    try:
        stamp = datetime.strptime(old["generated"], "%Y-%m-%dT%H:%M:%SZ") \
                        .replace(tzinfo=timezone.utc)
    except (KeyError, TypeError, ValueError):
        return True  # unreadable stamp -- rewrite rather than freeze it
    return (now - stamp).total_seconds() >= heartbeat_sec


def fetch_json(req, attempts=MAX_ATTEMPTS):
    """GET + parse with exponential backoff. 4xx (except 429) is deterministic -- fail fast."""
    last = None
    for i in range(attempts):
        try:
            with urllib.request.urlopen(req, timeout=15) as resp:
                return json.loads(resp.read())
        except urllib.error.HTTPError as e:
            if 400 <= e.code < 500 and e.code != 429:
                sys.exit(f"ERROR: CMC returned HTTP {e.code}: "
                         f"{e.read().decode('utf-8', 'replace')}")
            last = e
        except Exception as e:
            last = e
        if i < attempts - 1:
            time.sleep(BACKOFF_SEC * (2 ** i))
    sys.exit(f"ERROR: CMC fetch failed after {attempts} attempts: {last}")


def main():
    api_key = os.environ.get("CMC_API_KEY")
    if not api_key:
        sys.exit("ERROR: CMC_API_KEY environment variable is not set")

    print("Fetching Fear & Greed index from CoinMarketCap...")
    req = urllib.request.Request(URL, headers={
        "X-CMC_PRO_API_KEY": api_key,
        "Accept":            "application/json",
        "User-Agent":        "btcticker-fng/1.0",
    })
    raw = fetch_json(req)

    status = raw.get("status") or {}
    # error_code comes back as a string ("0" on success), so compare loosely
    if str(status.get("error_code", "0")) not in ("0", ""):
        sys.exit(f"ERROR: CMC returned error {status.get('error_code')}: {status.get('error_message')}")

    # Response: {"data": {"value": 73, "value_classification": "Greed",
    #            "update_time": "2023-..."}, "status": {...}}
    data = raw.get("data") or {}
    try:
        value = int(round(float(data["value"])))
    except (KeyError, TypeError, ValueError):
        sys.exit(f"ERROR: no usable value in CMC response: {data}")
    classification = data.get("value_classification", "")

    now = datetime.now(timezone.utc)
    payload = {
        "generated":      now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "update_time":    data.get("update_time", ""),
        "value":          value,
        "classification": classification,
    }

    if "--force" not in sys.argv and not should_write(read_existing(OUT_FILE), payload, now):
        print(f"Unchanged (value={value}, stamp still fresh) -- leaving {OUT_FILE} untouched")
        return

    js = (
        "// Auto-generated by fetch_fng.py -- do not edit manually\n"
        f"window.LOCAL_FNG = {json.dumps(payload, separators=(',', ':'))};\n"
    )
    # atomic replace so an interrupted run can't leave a truncated fng.js
    fd, tmp = tempfile.mkstemp(dir=OUT_FILE.parent, suffix=".tmp")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(js)
    os.replace(tmp, OUT_FILE)
    print(f"Written {OUT_FILE}: value={value} ({classification})")


if __name__ == "__main__":
    main()
