#!/usr/bin/env python3
"""
Fetch 30 days of CDC Action Zone blocks from Kraken and write to data/cdc.js.
Run manually or via cron: 5 0 * * * cd /path/to/btcticker && python3 fetch_cdc.py

Uses Kraken (not Binance) -- Binance blocks GitHub Actions IP ranges (HTTP 451).
"""

import json
import os
import sys
import tempfile
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

DISPLAY  = 30    # blocks to show
LIMIT    = 100   # candles to use for EMA warmup (Kraken returns up to 720)
OUT_FILE = Path(__file__).parent / "data" / "cdc.js"
# interval=1440 = 1 day in minutes; close price is index 4 in each row
URL      = "https://api.kraken.com/0/public/OHLC?pair=XBTUSD&interval=1440"


def calc_ema(closes, period):
    k   = 2 / (period + 1)
    out = [None] * len(closes)
    out[period - 1] = sum(closes[:period]) / period
    for i in range(period, len(closes)):
        out[i] = closes[i] * k + out[i - 1] * (1 - k)
    return out


def main():
    print("Fetching daily candles from Kraken...")
    req = urllib.request.Request(URL, headers={"User-Agent": "btcticker-cdc/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            raw = json.loads(resp.read())
    except Exception as e:
        sys.exit(f"ERROR: Kraken fetch failed: {e}")

    if raw.get("error"):
        sys.exit(f"ERROR: Kraken returned error: {raw['error']}")

    # Response: {"result": {"XXBTZUSD": [[time,o,h,l,close,vwap,vol,count],...], "last":...}}
    result   = raw.get("result") or {}
    pair_key = next((k for k in result if k != "last"), None)
    if pair_key is None:
        sys.exit("ERROR: no pair data in Kraken response")
    candles  = result[pair_key][-LIMIT:]   # take last LIMIT rows
    closes   = [float(c[4]) for c in candles]

    # 26-candle EMA warmup plus 30 display blocks; a shorter response would
    # silently produce wrapped/garbage blocks via negative indexing
    if len(closes) < DISPLAY + 26:
        sys.exit(f"ERROR: only {len(closes)} candles, need {DISPLAY + 26}")

    ema12 = calc_ema(closes, 12)
    ema26 = calc_ema(closes, 26)

    blocks = []
    for i in range(len(closes) - DISPLAY, len(closes)):
        blocks.append({
            "bull":  ema12[i] > ema26[i],
            "today": i == len(closes) - 1,
            "diff":  round(abs(ema12[i] - ema26[i]), 2),
        })

    payload = {
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "blocks":    blocks,
    }

    js = (
        "// Auto-generated by fetch_cdc.py -- do not edit manually\n"
        f"window.LOCAL_CDC = {json.dumps(payload, separators=(',', ':'))};\n"
    )
    # atomic replace so an interrupted run can't leave a truncated cdc.js
    fd, tmp = tempfile.mkstemp(dir=OUT_FILE.parent, suffix=".tmp")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(js)
    os.replace(tmp, OUT_FILE)
    print(f"Written {len(blocks)} blocks to {OUT_FILE}")
    print(f"Last block -- bull: {blocks[-1]['bull']}, diff: {blocks[-1]['diff']}")


if __name__ == "__main__":
    main()
