#!/usr/bin/env python3
"""
Fetch 30 days of CDC Action Zone blocks from Binance and write to data/cdc.js.
Run manually or via cron: 0 0 * * * cd /path/to/btcticker && python3 fetch_cdc.py
"""

import json
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

LIMIT      = 100   # candles fetched — enough warmup for EMA26 (26 * 2 + 30 display)
DISPLAY    = 30    # blocks to show
OUT_FILE   = Path(__file__).parent / "data" / "cdc.js"
URL        = f"https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1d&limit={LIMIT}"


def calc_ema(closes, period):
    k   = 2 / (period + 1)
    out = [None] * len(closes)
    out[period - 1] = sum(closes[:period]) / period
    for i in range(period, len(closes)):
        out[i] = closes[i] * k + out[i - 1] * (1 - k)
    return out


def main():
    print(f"Fetching {LIMIT} daily candles from Binance...")
    req = urllib.request.Request(URL, headers={"User-Agent": "btcticker-cdc/1.0"})
    with urllib.request.urlopen(req, timeout=15) as resp:
        raw = json.loads(resp.read())

    closes = [float(k[4]) for k in raw]
    ema12  = calc_ema(closes, 12)
    ema26  = calc_ema(closes, 26)

    blocks = []
    for i in range(len(closes) - DISPLAY, len(closes)):
        blocks.append({
            "bull":  ema12[i] > ema26[i],
            "today": i == len(closes) - 1,
            "diff":  round(abs(ema12[i] - ema26[i]), 2),
        })

    payload = {
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "blocks":    blocks,
    }

    js = f"// Auto-generated by fetch_cdc.py — do not edit manually\nwindow.LOCAL_CDC = {json.dumps(payload, separators=(',', ':'))};\n"
    OUT_FILE.write_text(js, encoding="utf-8")
    print(f"Written {len(blocks)} blocks to {OUT_FILE}")
    print(f"Last block — bull: {blocks[-1]['bull']}, diff: {blocks[-1]['diff']}")


if __name__ == "__main__":
    main()
