"""Smoke tests on the committed data/*.js artefacts -- catches a corrupted or
malformed bot commit before it reaches a browser. Reuses fetch_fng.read_existing
(the same parser the should_write guard runs) so that parser gets exercised
against real committed files too, not just synthetic ones.
"""
import re
import sys
import unittest
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import fetch_cdc
import fetch_fng

REPO_ROOT = Path(__file__).resolve().parent.parent
CDC_FILE = REPO_ROOT / "data" / "cdc.js"
FNG_FILE = REPO_ROOT / "data" / "fng.js"


def _parse_timestamp(s):
    return datetime.strptime(s, "%Y-%m-%dT%H:%M:%SZ")


class CDCDataFileTests(unittest.TestCase):
    def setUp(self):
        self.text = CDC_FILE.read_text(encoding="utf-8")
        self.payload = fetch_cdc.read_existing(CDC_FILE)

    def test_has_autogenerated_banner(self):
        self.assertTrue(self.text.startswith("// Auto-generated by fetch_cdc.py"))

    def test_parses(self):
        self.assertIsNotNone(self.payload)

    def test_exactly_30_blocks(self):
        self.assertEqual(len(self.payload["blocks"]), 30)

    def test_block_shape(self):
        for i, b in enumerate(self.payload["blocks"]):
            with self.subTest(index=i):
                self.assertIsInstance(b["bull"], bool)
                self.assertIsInstance(b["today"], bool)
                self.assertIsInstance(b["diff"], (int, float))

    def test_only_last_block_is_today(self):
        flags = [b["today"] for b in self.payload["blocks"]]
        self.assertEqual(flags, [False] * 29 + [True])

    def test_generated_timestamp_parses(self):
        _parse_timestamp(self.payload["generated"])  # raises on malformed


class FNGDataFileTests(unittest.TestCase):
    def setUp(self):
        self.text = FNG_FILE.read_text(encoding="utf-8")
        self.payload = fetch_fng.read_existing(FNG_FILE)

    def test_has_autogenerated_banner(self):
        self.assertTrue(self.text.startswith("// Auto-generated by fetch_fng.py"))

    def test_parses(self):
        self.assertIsNotNone(self.payload)

    def test_value_in_range(self):
        self.assertGreaterEqual(self.payload["value"], 0)
        self.assertLessEqual(self.payload["value"], 100)

    def test_classification_present(self):
        self.assertTrue(self.payload["classification"])

    def test_generated_timestamp_parses(self):
        _parse_timestamp(self.payload["generated"])  # raises on malformed


if __name__ == "__main__":
    unittest.main()
